### PR TITLE
[RDY] feat: smoother donate icon and logo in svg

### PR DESCRIPTION
**Pull request by mrxyo**

### CODE REVIEW

**Comment by deuzu** [comment]
@patpetit A little screenshot to tease us?

**Comment by vandamic** [comment]
@deuzu  A [video](https://www.dropbox.com/s/2p4lmw6x9gk90d1/24chevres-smoother.mov?dl=0 ) should do the trick

**Comment by deuzu** [comment]
@patpetit If the pull request is ready to be merged, prefix the PR description with `[RDY]`

**Comment by izeau** [comment]
This is bullshirt. Getting really tired of this forking management.

**Comment by deuzu** [comment]
@izeau Yeah I know =(. I wanted to have a PR merging open to every one inside and outside the organisation that has a vote system. 
If you have an idea to avoid forks for organisation member but keeping the forced vote system please share.

**Pull request merged**
